In [1]:
#Import needed libraries 
import pandas as pd 
import os
from datetime import timedelta
from dotenv import load_dotenv
import numpy as np 
from scipy.signal import argrelextrema
import alpaca_trade_api as tradeapi

In [2]:
# Load .env environment variables
load_dotenv()

# Set Alpaca API key and secret
alpaca_api_key = os.getenv("ALPACA_API_KEY")
alpaca_secret_key = os.getenv("ALPACA_SECRET_KEY")

api = tradeapi.REST(
    alpaca_api_key,
    alpaca_secret_key,
    api_version='v2')

In [7]:
# Set the ticker
ticker = "TSLA"

# Set timeframe to "1 Minute"
timeframe = "1Min"

# Set start and end datetimes of 3 years from Today
start_date = pd.Timestamp("2021-12-15", tz="America/New_York").isoformat()
end_date = pd.Timestamp("2023-12-15", tz="America/New_York").isoformat()

# Get 3 years worth of historical data for TSLA
ticker_data = api.get_bars(
    ticker,
    timeframe,
    start=start_date,
    end=end_date,
).df

display(ticker_data.head())
display(ticker_data.tail())

sleep 3 seconds and retrying https://data.alpaca.markets/v2/stocks/TSLA/bars 3 more time(s)...
sleep 3 seconds and retrying https://data.alpaca.markets/v2/stocks/TSLA/bars 3 more time(s)...

,close,high,low,trade_count,open,volume,vwap
timestamp,,,,,,,
2021-12-15 09:00:00+00:00,955.22,955.22,955.22,54,955.22,547,955.377934
2021-12-15 09:01:00+00:00,955.00,955.10,955.00,69,955.00,1278,955.015548
2021-12-15 09:02:00+00:00,953.00,953.00,953.00,73,953.00,1513,953.177561
2021-12-15 09:03:00+00:00,952.36,952.36,951.74,74,951.74,853,951.862708
2021-12-15 09:05:00+00:00,953.40,953.40,953.34,41,953.34,498,953.339036

,close,high,low,trade_count,open,volume,vwap
timestamp,,,,,,,
2023-12-15 00:55:00+00:00,250.35,250.40,250.35,82,250.40,3199,250.377887
2023-12-15 00:56:00+00:00,250.35,250.40,250.34,78,250.35,6955,250.384772
2023-12-15 00:57:00+00:00,250.37,250.40,250.34,72,250.39,8737,250.378396
2023-12-15 00:58:00+00:00,250.44,250.45,250.40,56,250.40,3979,250.436761
2023-12-15 00:59:00+00:00,250.25,250.44,250.25,167,250.40,15411,250.356306